import { Caregiver, CareRequest, User } from '@/types/caregiver';

export const mockCaregivers: Caregiver[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    rating: 4.9,
    reviewCount: 127,
    hourlyRate: 35,
    specialties: ['Elderly Care', 'Dementia Care', 'Medication Management'],
    certifications: ['CNA', 'CPR Certified', 'First Aid'],
    experience: 8,
    bio: 'Compassionate caregiver with 8 years of experience specializing in elderly care and dementia support. Dedicated to providing dignified, personalized care.',
    location: 'San Francisco, CA',
    availability: [
      { day: 'Monday', startTime: '08:00', endTime: '18:00' },
      { day: 'Tuesday', startTime: '08:00', endTime: '18:00' },
      { day: 'Wednesday', startTime: '08:00', endTime: '18:00' },
    ],
    languages: ['English', 'Spanish'],
    isVerified: true,
    isAvailable: true,
  },
  {
    id: '2',
    name: 'Michael Chen',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    rating: 4.8,
    reviewCount: 94,
    hourlyRate: 32,
    specialties: ['Palliative Care', 'Physical Therapy', 'Hospice Care'],
    certifications: ['RN', 'BLS', 'Palliative Care Certification'],
    experience: 12,
    bio: 'Registered nurse with extensive experience in palliative and hospice care. Skilled in pain management and providing comfort to terminally ill patients.',
    location: 'Oakland, CA',
    availability: [
      { day: 'Monday', startTime: '12:00', endTime: '22:00' },
      { day: 'Thursday', startTime: '12:00', endTime: '22:00' },
      { day: 'Friday', startTime: '12:00', endTime: '22:00' },
    ],
    languages: ['English', 'Mandarin'],
    isVerified: true,
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Maria Rodriguez',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    rating: 5.0,
    reviewCount: 156,
    hourlyRate: 40,
    specialties: ['Alzheimer\'s Care', 'Companionship', 'Meal Preparation'],
    certifications: ['CNA', 'Alzheimer\'s Care Specialist'],
    experience: 10,
    bio: 'Patient and nurturing caregiver specializing in Alzheimer\'s care. Focused on creating a safe, engaging environment for clients with memory challenges.',
    location: 'San Jose, CA',
    availability: [
      { day: 'Tuesday', startTime: '07:00', endTime: '17:00' },
      { day: 'Wednesday', startTime: '07:00', endTime: '17:00' },
      { day: 'Saturday', startTime: '09:00', endTime: '17:00' },
    ],
    languages: ['English', 'Spanish', 'Portuguese'],
    isVerified: true,
    isAvailable: true,
  },
  {
    id: '4',
    name: 'David Thompson',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    rating: 4.7,
    reviewCount: 73,
    hourlyRate: 30,
    specialties: ['Mobility Assistance', 'Personal Care', 'Transportation'],
    certifications: ['HHA', 'CPR Certified'],
    experience: 5,
    bio: 'Dedicated home health aide with a focus on mobility assistance and personal care. Committed to helping clients maintain independence and dignity.',
    location: 'Palo Alto, CA',
    availability: [
      { day: 'Monday', startTime: '09:00', endTime: '19:00' },
      { day: 'Friday', startTime: '09:00', endTime: '19:00' },
      { day: 'Sunday', startTime: '10:00', endTime: '18:00' },
    ],
    languages: ['English'],
    isVerified: true,
    isAvailable: true,
  },
  {
    id: '5',
    name: 'Jennifer Park',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop',
    rating: 4.9,
    reviewCount: 201,
    hourlyRate: 45,
    specialties: ['Post-Surgery Care', 'Wound Care', 'Medication Administration'],
    certifications: ['RN', 'Wound Care Certification', 'IV Therapy'],
    experience: 15,
    bio: 'Highly skilled registered nurse specializing in post-surgical care and wound management. Provides professional medical care with a gentle touch.',
    location: 'Mountain View, CA',
    availability: [
      { day: 'Wednesday', startTime: '08:00', endTime: '20:00' },
      { day: 'Thursday', startTime: '08:00', endTime: '20:00' },
      { day: 'Saturday', startTime: '08:00', endTime: '16:00' },
    ],
    languages: ['English', 'Korean'],
    isVerified: true,
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Robert Williams',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    rating: 4.6,
    reviewCount: 58,
    hourlyRate: 28,
    specialties: ['Overnight Care', 'Companionship', 'Light Housekeeping'],
    certifications: ['CNA', 'First Aid'],
    experience: 4,
    bio: 'Reliable and trustworthy caregiver providing overnight care and companionship. Ensures safety and comfort throughout the night.',
    location: 'Berkeley, CA',
    availability: [
      { day: 'Monday', startTime: '20:00', endTime: '08:00' },
      { day: 'Tuesday', startTime: '20:00', endTime: '08:00' },
      { day: 'Friday', startTime: '20:00', endTime: '08:00' },
    ],
    languages: ['English'],
    isVerified: true,
    isAvailable: true,
  },
];

export const mockRequests: CareRequest[] = [
  {
    id: 'req-1',
    caregiverId: '1',
    caregiverName: 'Sarah Johnson',
    caregiverAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    status: 'confirmed',
    startDate: '2026-04-15',
    endDate: '2026-04-15',
    startTime: '09:00',
    endTime: '17:00',
    notes: 'Mother needs assistance with daily activities and medication reminders.',
    totalAmount: 280,
    careType: 'Daily Care',
    patientName: 'Margaret Wilson',
    address: '123 Oak Street, San Francisco, CA',
    createdAt: '2026-04-10T10:30:00Z',
  },
  {
    id: 'req-2',
    caregiverId: '3',
    caregiverName: 'Maria Rodriguez',
    caregiverAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    status: 'pending',
    startDate: '2026-04-18',
    endDate: '2026-04-20',
    startTime: '08:00',
    endTime: '16:00',
    notes: 'Weekend care for father with early-stage Alzheimer\'s.',
    totalAmount: 640,
    careType: 'Respite Care',
    patientName: 'James Anderson',
    address: '456 Pine Avenue, San Jose, CA',
    createdAt: '2026-04-09T14:20:00Z',
  },
  {
    id: 'req-3',
    caregiverId: '2',
    caregiverName: 'Michael Chen',
    caregiverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    status: 'completed',
    startDate: '2026-04-01',
    endDate: '2026-04-05',
    startTime: '12:00',
    endTime: '20:00',
    notes: 'Post-surgery recovery assistance.',
    totalAmount: 1280,
    careType: 'Recovery Care',
    patientName: 'Robert Chen',
    address: '789 Maple Road, Oakland, CA',
    createdAt: '2026-03-28T09:00:00Z',
  },
];

export const mockUser: User = {
  id: 'user-1',
  name: 'Emily Thompson',
  email: 'emily.thompson@email.com',
  avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
  phone: '+1 (555) 123-4567',
  address: '123 Main Street, San Francisco, CA 94102',
  role: 'family',
};
